### ISSUE TITLE
View Invariance

### ISSUE THREAD

**Issue by JiaheXu** [YanjieZe/Improved-3D-Diffusion-Policy#10]
Hi Yanjie,

Exciting work, I am curious how you achieved View invariance? Did you collect data from different views during data collection or using data-aug in 3D for variant views? What's the action space frame and robot state frame(for EE), are you using camera frame for EE?

**Comment by YanjieZe** [comment]
Hi, thank you for your interest. The view invariance is achieved via using our 3D representation. We do not collect data from different views. We use joint positions as action/state.

**Comment by JiaheXu** [comment]
when you collect data, does the robot move?

**Comment by YanjieZe** [comment]
We do not use camera pose; but yea, the camera is moving (as shown in our videos) due to the head move.

**Comment by Josh00-Lu** [comment]
> Hi, thank you for your interest. The view invariance is achieved via using our 3D representation. We do not collect data from different views. We use joint positions as action/state.

Hi Yanjie,

I am particularly amazed by [this video](https://humanoid-manipulation.github.io/videos/view_invariant/idp3.mp4). iDP3 uses local frame, did you do active transformation to transfer the 3D cloud-point input to world frame? I am wondering since the training stage uses joint positions (We use joint positions as action/state.), how do you make sure the policy will not just learn to abandon the 3D representation and just turn to joint position inputs?
