### ISSUE TITLE
Data set related consulting

### ISSUE THREAD

**Issue by tobottyx** [YanjieZe/Improved-3D-Diffusion-Policy#5]
Thank you for providing your method and would like to ask questions about the amount of data in the collected dataset. I found that in the dataset you provided, there are 541 actions, 259 in one and 282 in the other. May I ask how to control the number of episodes? For the same class of tasks, only two tracks are needed? I feel a little weird

**Comment by YanjieZe** [comment]
Hi, it is an example dataset that is used as an example. The two trajectories are sampled from the full dataset. the full dataset is much larger, which I will upload in a few days.
The main reason I do not upload full datasets is just it might not be helpful for you since most people do not have the exactly same robot, so I put 2 episodes to show how the trajectory look like.
